stylelint/stylelint-config-recommended

package-lock.json, package.json
=> chore: Update remark

index.js, package.json
=> Add new 8.3 rules

__tests__/index.test.js
=> Apply jest/prefer-to-have-length

package.json
=>  Update `eslint-config-stylelint` to 8.3.0.

README.md
See also:
- https://github.com/stylelint/stylelint/blob/9.7.0/CHANGELOG.md#970
- stylelint/stylelint#3642
- stylelint/stylelint-config-standard#123
=> Add more simple usage for globally installed configs

.travis.yml, CHANGELOG.md, appveyor.yml, package.json
Preparing for stylelint@10 release.
Merge after stylelint@10 release.
=> Add stylelint@10 to peer dependency range

package.json
The primary purpose of this PR is to ensure `npm audit` results are ✅
```shell
added 70 packages from 61 contributors, removed 84 packages, updated 81 packages, moved 15 packages and audited 865588 packages in 13.103s
found 0 vulnerabilities
```
=> chore: update Jest

.travis.yml
https://github.com/stylelint/stylelint/issues/4244
Also removed Node.js 8 from Travis, because we test it in the stylelint repository.
=> Use Dependabot

.npmrc, package.json
https://github.com/stylelint/stylelint/pull/4243
=> Use np for publishing

package.json
=> Fixed typo in lint-staged

CHANGELOG.md, index.js, package-lock.json, package.json
Closes #80 
Tests will fail until stylelint `13.12.0` is released.
This will be released as `4.0.0`.
=> Add two new possible error rules

index.js
Fixes https://github.com/stylelint/stylelint-config-recommended/issues/94
=> Ignore Custom Elements in selector-type-no-unknown

index.js, package-lock.json, package.json
None.
New "possible error" rules.
Tests will fail until `13.13.0` is released. Tested locally with `master`, though.
=> Add new at-import and whitespace rules

index.js
Closes #121
Only removes a single rule.
=> Remove function-calc-no-invalid rule

.github/workflows/nodejs.yml, package-lock.json, package.json
None
Brings scripts in line with the latest conventions used in our other repos.
=> Update workflow and husky commands

CHANGELOG.md, index.js, package-lock.json, package.json
None
Tests will pass once stylelint@14.4.0 is released.
=> Add function-no-unknown

.github/workflows/nodejs.yml, package-lock.json, package.json
None.
Preparing for Stylelint 14.8.1 (see <https://github.com/stylelint/stylelint/issues/6043>)
=> Update deps and CI settings

CHANGELOG.md, index.js, package-lock.json, package.json
Close #169
Tests will pass when 14.10 is released.
=> Prepare 9.0.0

CHANGELOG.md, __tests__/index.test.js, index.js
None.
We missed a deprecated rule.
=> Prepare 10.0.1

CHANGELOG.md, index.js, package-lock.json, package.json
Ref: https://github.com/stylelint/stylelint/issues/6698
`declaration-property-value-no-unknown` has been out for a month or so now. Shall we include it in this release too?
=> Prepare 11.0.0

CHANGELOG.md, __tests__/index.test.js, index.js, package-lock.json, package.json
Closes #186
Changes summary:
- Require `stylelint@15.5.0` as the next version.
- Change `declaration-block-no-duplicate-properties` option to `ignore: ['consecutive-duplicates-with-different-values']`.
- Update dependencies.
- Refactor the test code for readability.
=> Prepare 12.0.0

.github/workflows/release.yml
Using the org-wide action: https://github.com/stylelint/changelog-to-github-release-action
None.
=> Automate releasing on GitHub

CHANGELOG.md, index.js, package-lock.json, package.json
=> Prepare 16.0.0
